version: '3'


tasks:
  compose:
    preconditions:
      - test -f docker/docker-compose.yml
    cmds:
      - docker compose -f docker/docker-compose.yml up -d

  dev-up:
    preconditions:
      - test -f docker/docker-compose.dev.yml
    cmds:
      - docker compose -f docker/docker-compose.dev.yml up -d

  dev-stop:
    preconditions:
      - test -f docker/docker-compose.dev.yml
    cmds:
      - docker compose -f docker/docker-compose.dev.yml stop

  schema-apply:
    env:
      DATABASE_URL: "postgres://{{.DB_USERNAME}}:{{.DB_PASSWORD}}@localhost:5432/{{.DB_DATABASE_NAME}}?sslmode=disable"
    cmds:
      - atlas schema apply --env dev

  start:
    preconditions:
      - test -f src/config.yml
    cmds:
      - uvicorn launcher:app --app-dir=src --reload-exclude=venv --reload
    silent: true
  
  check:
    cmds:
      - pyright src
      - ruff check server --fix --exit-non-zero-on-fix
    silent: true

  ruff:
    cmds:
      - ruff check src --fix --exit-non-zero-on-fix
      - ruff format src
    silent: true
