# This file is not settable during runtime.
# If you wish to change the values, change and save, and restart your server

server:

  # Host that the server will use.
  # Set to 0.0.0.0 if running in Docker
  host: "localhost"

  # Port that the server binds to.
  # Defaults to 8000
  port: 8000

# The PostgreSQL connection URI that is used to connect to the database
# The URI must be valid, and components will need to be quoted.
# See https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
postgres_uri: "postgresql://postgres:K5c8FQMicq5p8yVXpDPeREl35u2qP5t3u5K8dhn8CzPRhyYL@localhost:5432/kanae"