name: template_dev

services:
  database:
    container_name: template_postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    ports:
      - 6379:6379
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RMQ_PASSWORD}
    hostname: broker-rabbit
    ports:
      - 5672:5672
      - 8080:15672
    env_file:
      - .env
    restart: always

volumes:
  database: